title: Dr. Venkatesh Nagarajan Radha
email: venkatesh.nagarajan@sydney.edu.au
description: >-
  Researcher in ecology and evolutionary biology, focusing on the evolutionary impact of climate change.
baseurl: ""
url: "https://yourgithubusername.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
include: ["_pages"]
